### ISSUE TITLE
Using 'Gulp+Browserify' to build gtfs-validator-webapp instead of 'Component'

### ISSUE THREAD

**Issue by mohangandhiGH** [conveyal/gtfs-validator#35]
@sheldonabrown @laidig We are currently using gtfs-validator-webapp in https://github.com/CUTR-at-USF/gtfs-realtime-validator project. Using `component` to build gtfs-validator-webapp is causing to have some restrictions on build process. I do also remember laidig mentioning about switching to another build process as 'Component' is deprecated. So, if this is okay, we would like to make changes to the build process of gtfs-validator-webapp to use `Gulp+Browserify`. 
Cc'd @barbeau

**Comment by barbeau** [comment]
IIRC the issue that we're seeing with using Component to build is generating Symlinks on Windows.  As a result, you'd have to run the gtfs-realtime-validator as an admin in order to see the static validation results.  We'd obviously like to avoid that if possible, and updating the build process to use Gulp + Browserify would let us get rid of the admin permission requirement.

@laidig's previous comment on ditching Component is at https://github.com/laidig/gtfs-validator/issues/6#issuecomment-276254500.

@mohangandhiGH I think you already had a proof-of-concept of this running?  If so, could you please go ahead and open a pull request with it so @laidig and @sheldonabrown can take a look?

**Comment by mohangandhiGH** [comment]
@barbeau I will do that Sean.
