### ISSUE TITLE
OutOfMemoryError w/ ~175MB Gtfs file

### ISSUE THREAD

**Issue by russellhoff** [conveyal/gtfs-validator#38]
I was trying to validate a gtfs built at work, which is really heavy: 175.745 KB. The issue came when trying to read ShapePoints, as shapes.txt is weighted at almost 1GB (948.669.709 B):

> PS D:\gtfs-apps\gtfs-validator\gtfs-validation-lib\target> java -jar .\gtfs-validator.jar W:\gtfs-finales\gtfs-bizkaibus.zip
> Reading GTFS from W:\gtfs-finales\gtfs-bizkaibus.zip
> [main] INFO org.onebusaway.gtfs.serialization.GtfsReader - reading entities: org.onebusaway.gtfs.model.Agency
> [main] INFO org.onebusaway.gtfs.serialization.GtfsReader - reading entities: org.onebusaway.gtfs.model.Block
> [main] INFO org.onebusaway.gtfs.serialization.GtfsReader - reading entities: org.onebusaway.gtfs.model.ShapePoint
> Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
>         at java.lang.StringBuilder.toString(Unknown Source)
>         at org.onebusaway.csv_entities.DelimitedTextParser.parse(DelimitedTextParser.java:136)
>         at org.onebusaway.csv_entities.CSVLibrary.parse(CSVLibrary.java:131)
>         at org.onebusaway.csv_entities.CsvTokenizerStrategy.parse(CsvTokenizerStrategy.java:34)
>         at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:154)
>         at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:120)
>         at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:115)
>         at org.onebusaway.gtfs.serialization.GtfsReader.run(GtfsReader.java:174)
>         at org.onebusaway.gtfs.serialization.GtfsReader.run(GtfsReader.java:162)
>         at com.conveyal.gtfs.validator.ValidatorMain.main(ValidatorMain.java:54)

Is there any possibility that telling the jvm to make use of a larger heap that your validator will work with such a large file?

Thanks in advance!

**Comment by laidig** [comment]
You can try adding the options `-server -Xmx4G` . I have processed large
feeds with similar options.

On Apr 7, 2017 7:30 AM, "Jon I." <notifications@github.com> wrote:

I was trying to validate a gtfs built at work, which is really heavy:
175.745 KB. The issue came when trying to read ShapePoints, as shapes.txt
is weighted at almost 1GB (948.669.709 B):

PS D:\gtfs-apps\gtfs-validator\gtfs-validation-lib\target> java -jar
.\gtfs-validator.jar W:\gtfs-finales\gtfs-bizkaibus.zip Reading GTFS from
W:\gtfs-finales\gtfs-bizkaibus.zip [main] INFO
org.onebusaway.gtfs.serialization.GtfsReader
- reading entities: org.onebusaway.gtfs.model.Agency [main] INFO
org.onebusaway.gtfs.serialization.GtfsReader - reading entities:
org.onebusaway.gtfs.model.Block [main] INFO
org.onebusaway.gtfs.serialization.GtfsReader
- reading entities: org.onebusaway.gtfs.model.ShapePoint Exception in
thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded at
java.lang.StringBuilder.toString(Unknown Source) at
org.onebusaway.csv_entities.DelimitedTextParser.parse(DelimitedTextParser.java:136)
at org.onebusaway.csv_entities.CSVLibrary.parse(CSVLibrary.java:131) at
org.onebusaway.csv_entities.CsvTokenizerStrategy.parse(CsvTokenizerStrategy.java:34)
at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:154)
at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:120)
at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:115)
at org.onebusaway.gtfs.serialization.GtfsReader.run(GtfsReader.java:174) at
org.onebusaway.gtfs.serialization.GtfsReader.run(GtfsReader.java:162) at
com.conveyal.gtfs.validator.ValidatorMain.main(ValidatorMain.java:54)

Is there any possibility that telling the jvm to make use of a larger heap
that your validator will work with such a large file?

Thanks in advance!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/conveyal/gtfs-validator/issues/38>, or mute the thread

**Comment by laidig** [comment]
here are the command line params I use:
`java -server -Xmx4g -Xms3g -jar gtfs-validator.jar`
